# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Build
        run: |
          yarn
          yarn build
      - name: Dist
        if: ${{ secrets.VERCEL_PUBLISH_TOKEN }} != ''
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn dist
      - uses: actions/upload-artifact@v2
        if: ${{ secrets.VERCEL_PUBLISH_TOKEN }} != ''
        with:
          name: installer
          path: dist/*.exe
          if-no-files-found: error
